plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'org.olo'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api 'io.temporal:temporal-sdk:1.26.0'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            groupId = 'org.olo'
            artifactId = 'olo-temporal-sdk'
            version = project.version
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
